version: "3.8"
services:
  postgres_pgvector:
    image: ankane/pgvector:latest
    restart: always
    container_name: postgres_pgvector
    ports:
      - "5432:5432"
    env_file:
      - .env/pg.env  # Path to your .env file
    volumes:
      - mylife_pgvector_data:/var/lib/postgresql/data
      - ./scripts/sql:/docker-entrypoint-initdb.d
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: mylife-pgadmin
    ports:
      - "5050:80"
    env_file:
      - .env/pgadmin.env  # Path to your .env file
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_pgvector
  embedding-server:
#    image: mookse/mylife-embedding-server:latest
### relevant when building locally for development
    build:
      context: .  # Path to your text embedding server code
    container_name: mylife-embedding-server
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    env_file:
      - .env/embedder.env  # Path to your .env file
    depends_on:
      - postgres_pgvector
      
volumes:
  mylife_pgvector_data:
  pgadmin_data: