version: "3.8"
services:
  postgres_pgvector:
    image: ankane/pgvector:latest
    restart: always
    container_name: postgres_pgvector
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 7bT!!icgg&f%7MH
    volumes:
      - mylife_pgvector_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: mylife-pgadmin
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: 7bT!!icgg&f%7MH
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres_pgvector
  text-embedding-server:
    build:
      context: .  # Path to your text embedding server code
    container_name: mylife-embedding-server
    ports:
      - "8000:8000"  # Map host port 8000 to container port 8000
    env_file:
      - .env  # Path to your .env file
    depends_on:
      - postgres_pgvector
      
volumes:
  mylife_pgvector_data:
  pgadmin_data: